### ISSUE TITLE
Update sj.bloom.exygy.dev with SJ content and listings

### ISSUE THREAD

**Issue by jacchau** [housingbayarea/bloom#10]
Summary: Update sj.bloom.exygy.dev with SJ content from content inventory and listings

- [x] Update sj.bloom.exygy.dev based on the following content library https://docs.google.com/spreadsheets/d/17PSCoQD5vZiy5VNw1iO4V23IHv_PP8yiAZEi1IPkE2o/edit#gid=90925465

- [x] Create individual listing jsons from listings from sj.housingbayarea.org, listings.id = 4, 5, 6, 9 and related units, application_download_urls, and preferences files (only listing id 3 should have preference information) 

Reference - [sj.housingbayarea.org](url)

**Comment by jacchau** [comment]
HI @software-project, please see 'QA Change Log' tab here https://docs.google.com/spreadsheets/d/17PSCoQD5vZiy5VNw1iO4V23IHv_PP8yiAZEi1IPkE2o/edit#gid=249966519. Thank you for pushing this forward, we are so close! I need your help to prioritize the minor content changes and then create the listing jsons in the branch for the missing listings. I can take a stab on updating the individual listing jsons once they've been created. Can we merge the PR first and then work on these changes?

**Comment by jacchau** [comment]
Hi @software-project, just did a quick QA and found that (9) and (10) from this sheet needs to be fixed. I realized that I had missed the /disclaimer and /privacy page entirely. I've added these in rows (14) and (15). I will work with Ben on the process for listings so don't worry about those for now. Thank you!

**Comment by jacchau** [comment]
Going to reopen this issue as @software-project is working on a set of fixes in this QA change log https://docs.google.com/spreadsheets/d/17PSCoQD5vZiy5VNw1iO4V23IHv_PP8yiAZEi1IPkE2o/edit#gid=249966519

**Comment by kathyccheng** [comment]
Looks like content updates were merged, closing issue
