### ISSUE TITLE
Create Alameda Jones Listing - Developer: Greystar 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#111]
Listing Spreadsheet: https://docs.google.com/spreadsheets/d/115UvIwgeJb8B8YPpBunY53lhNBZz5tXvEkKSK8sDuEI/edit#gid=56577888

This is going to be our pilot for the Common Application! 

Target Launch Date: 
9/8/2020

**Comment by bk3c** [comment]
@software-project it sounds like they're still trying to decide on a final image, so let's use this one from the Greystar website in the meantime: https://www.greystar.com/dfsmedia/ec6d229c550048739bb0d58403fec24c/111826-50035

**Comment by kathyccheng** [comment]
@software-project they just sent over this image: https://drive.google.com/file/d/1s1Avhns9654YMLGT7lbnGVPHKMJ2prwx/view?usp=sharing
