### ISSUE TITLE
update Alameda privacy policy

### ISSUE THREAD

**Issue by bk3c** [housingbayarea/bloom#113]
@kathyccheng or @vubang228 - can you put a link to the final text here, and we can get it converted and formatted for the site?

**Comment by vubang228** [comment]
@bk3c its here, I think this will be the final version, but there are some unanswered questions on zach that I want him to confirm. essentially, the county counsel in a series of comments asked a question, zach answered with some potential edits and she just went ahead and approved the whole thing. So I wanted zach to confirm. doc is here: 
https://docs.google.com/document/d/11BA0ggHwSm1jtVzsneGKNKUhL-wX9t4G5dMqc8vUkLE/edit?usp=sharing

**Comment by kathyccheng** [comment]
@bk3c privacy policy language is finalized!
https://docs.google.com/document/d/11BA0ggHwSm1jtVzsneGKNKUhL-wX9t4G5dMqc8vUkLE/edit

**Comment by bk3c** [comment]
@dominikx96 This is still an open item for launch today, so can you give a try and getting this into MDX?

**Comment by dominikx96** [comment]
@bk3c sorry, I missed this task (I mostly used the main repo) - I'm working on it!

**Comment by bk3c** [comment]
Fixed by #153
