### ISSUE TITLE
add the PDF version of the Alameda Common Application

### ISSUE THREAD

**Issue by bk3c** [housingbayarea/bloom#114]
Now that the PDF version of the Common Application for Alameda is reasonably finalized, we should add a version to `public` so that it's easy to link to.

**Comment by kathyccheng** [comment]
[Alameda Common Application Main.pdf](https://github.com/housingbayarea/bloom/files/5158968/Alameda.Common.Application.Main.pdf)

**Comment by kathyccheng** [comment]
@bk3c confirmed!

**Comment by bk3c** [comment]
@kathyccheng It's not a huge deal, but can we see why the PDF is so big? >2MB for a short PDF with just small logos seems excessive to me.
