### ISSUE TITLE
Implement localization v1 for Alameda

### ISSUE THREAD

**Issue by bk3c** [housingbayarea/bloom#12]
Note that we probably want to implement some of the strings into core product, since they should be the same for all jurisdictions, and then the rest can be shared between housingbayarea jurisdictions unless there's reason to think that they're county-specific. (@jacchau - sharing translations is an excellent topic for a future regional steering committee meeting from my perspective, so maybe you and I could work putting a deck together about it?)

**"Essential" languages to include:**

These are the highest priority localizations, but it's not clear whether they'll truly block the initial launch while they figure out who can own getting the translated strings correct on their end, or whether we can go ahead english only with "coming soon" links while translation is finalized.

- Chinese (check what is more inclusive, traditional or simple)
- Spanish
- For Oakland, Vietnamese is essential and mandatory, so that will likely be #3 based on how quickly we're going to have an Oakland-based listing.

**Nice to have** (probably post v1)
- Fremont: Has a big Afghan and Indian population, Farsi, Hindi, Punjabi
- Livermore:  Farsi, Hindi

There are definitely concerns on the county side about maintaining/updating the selected language translations, so anything we can do to document the process clearly is going to be a big help.

(cc: @antonelitum)

**Comment by bk3c** [comment]
This isn't quite Ready for Development, but it should be within the next week or two. Alameda has selected and engaged with their vendor for translations, and we're hoping for a call with them this week to agree on a process. Note this probably depends on https://github.com/bloom-housing/bloom/pull/307 among other things.

**Comment by kathyccheng** [comment]
Closing in favor of #188
