### ISSUE TITLE
[SMC] Re-create SMC Brunswick Listing 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#132]
Spreadsheet with updated values: 
https://docs.google.com/spreadsheets/d/1fEMkqROkJjR_z6pWvj2XqHyQEt8g_aCJr2uhKNmu_PY/edit#gid=0

Updates: 
There are no 50% AMI units available.
The 60% AMI rent is now $1,789.
The minimum monthly income limit is 2,684.
Max income limit for 1 person is $73,080
Max income limit for 2 persons is $83,520
Amenities include
* Underground parking
* Fitness center
* Large community room
* On-site laundry rooms
* Outdoor picnic/seating area
* Stunning views of the SF Bay
* On-site Van service
* 2 elevators

The name of the management company is Aperto Property Management, Inc.
We have had professional pics taken of the furnished model and exterior of the property.  Once I receive them, I will forward.
We are accepting applications for immediate move-in

Target re-launch date: 
TBD

**Comment by software-project** [comment]
@kathyccheng spreadsheet suggests that there are 21 50% units, which one is correct?

**Comment by kathyccheng** [comment]
@software-project I added a Update 10/2020 tab into the spreadsheet to capture what updates they want to make. Hopefully that's clearer now! 

https://docs.google.com/spreadsheets/d/1fEMkqROkJjR_z6pWvj2XqHyQEt8g_aCJr2uhKNmu_PY/edit#gid=1926448597

**Comment by kathyccheng** [comment]
Closing, can be done in listings mgmt
