### ISSUE TITLE
Final SAHA Monarch QA

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#160]
Here are the final QA items: 
* Change leasing address from 3268 San Pablo Ave Oakland, CA 94608 to 3250 San Pablo Ave Oakland, CA 94608.
* Change rent from $1470 to $0 

Updated in QA tab in yellow too: 
https://docs.google.com/spreadsheets/d/1eHAiiHPTCifAK73YLgjO4roLHzz5We2kaU_MJYnMD5g/edit#gid=2062100322

@bk3c @software-project

**Comment by kathyccheng** [comment]
Okay @bk3c @software-project I think this is the final item. We're changing the rent to $0 because it's a sliding range from $0-1470 instead of showing the top number first  

![image](https://user-images.githubusercontent.com/3453407/94185442-1faa7d00-fe5a-11ea-9c2a-024cbc4c3067.png)

**Comment by bk3c** [comment]
@kathyccheng (cc: @slowbot) are we really sure we want to set this to $0 with no other context? I'll defer to any actual research, but it seems like it'll be mostly confusing to most users, even though I understand it'll be correct for some folks.

**Comment by software-project** [comment]
@bk3c I'm looking into that bug. Rent range is not calculated correctly actually

**Comment by bk3c** [comment]
Oh, perfect. Showing the range would be ideal.

**Comment by software-project** [comment]
@bk3c there was a bug in min-max function 0 was taken as undefined so it got reseted. PR is ready on bloom-housing
