### ISSUE TITLE
Logan QA Items 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#172]
Latest QA Round on Logan 
Trying to Launch Application by Wed 10/15

https://docs.google.com/spreadsheets/d/1JV9OtmBctKK93hnBrl0dQdBKPE6qYnunQYlP-Zw8eD4/edit#gid=1804508109

**Comment by vubang228** [comment]
@kathyccheng @software-project updated QA: https://docs.google.com/spreadsheets/d/1JV9OtmBctKK93hnBrl0dQdBKPE6qYnunQYlP-Zw8eD4/edit?usp=sharing

**Comment by kathyccheng** [comment]
@software-project @bk3c a few updates: 
* Update download URL to: https://docs.google.com/spreadsheets/d/1JV9OtmBctKK93hnBrl0dQdBKPE6qYnunQYlP-Zw8eD4/edit#gid=1804508109
* Can we remove this section?
![image](https://user-images.githubusercontent.com/3453407/95945404-4267eb80-0d9f-11eb-8418-fec34fca6bdc.png)
