### ISSUE TITLE
Adjust View Resources Language 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#199]
Update copy on Homepage and Additional Resources page 

Homepage Button: 
View Additional Housing Opportunities and Resources 
![image](https://user-images.githubusercontent.com/3453407/104627904-74157a80-564c-11eb-9284-08fd6cb4cbcc.png)

Additional Resources Page Title: 
Additional Housing Opportunities and Resources 
![image](https://user-images.githubusercontent.com/3453407/104627995-8ee7ef00-564c-11eb-9df8-6596501ff54a.png)

**Comment by kathyccheng** [comment]
@netrabadami this seems to have gotten lost in the latest migration, can you take another look?

**Comment by netrabadami** [comment]
@kathyccheng because the change  was on housingbayarea master and not on 0.3_alameda.I have added the changes on 0.3-alameda now.

**Comment by kathyccheng** [comment]
Looks good
