### ISSUE TITLE
Spanish header too long 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#209]
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/8582aec4-fe8d-4260-a62d-0446fdbe8eb1)

Let's drop the second sentence in Spanish.

**Comment by netrabadami** [comment]
@kathyccheng  Are you saying something like this?

![Screen Shot 2021-02-05 at 1 22 34 PM](https://user-images.githubusercontent.com/58486174/107090640-55228800-67b5-11eb-8394-3ede594c532c.png)

**Comment by kathyccheng** [comment]
Closed with #207
