### ISSUE TITLE
Add Open House, Public Lottery, Close Date to SoHay

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#210]
**Add Open House and Public Lottery events to SoHay listing** 

_Open Houses_
3/3@2-3PM
[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2E0MThlMTgtNGUwMi00ODk3LWFkYTQtMmM4YzYzNTIwMTUz%40thread.v2/0?context=%7b%22Tid%22%3a%2215cb6c53-0a50-4876-a66c-9a753d760a7d%22%2c%22Oid%22%3a%2267252afa-99d8-45f9-93b0-91c740661a60%22%7d)

3/9@11AM-12PM
[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGI2OWUyNTMtMzIyNy00YWQ1LTllOTEtNzc4NmNjODJiNmJm%40thread.v2/0?context=%7b%22Tid%22%3a%2215cb6c53-0a50-4876-a66c-9a753d760a7d%22%2c%22Oid%22%3a%2267252afa-99d8-45f9-93b0-91c740661a60%22%7d)

_Public Lottery_
3/29 

**Update Application Close Date** 

_Application Close Date_ 
3/15/2021 5pm

**Comment by software-project** [comment]
@kathyccheng right now we can only add one open hours. To add multiple it would require a change on the main repo as well. Do you want me to do it?

**Comment by kathyccheng** [comment]
@software-project if it's a quick update, let's do it with the merge work now. Otherwise, let's just do this issue with the first Open House date and then merge it in. And we'll do the additional Open House separately.

**Comment by kathyccheng** [comment]
Merged in #213
