### ISSUE TITLE
Add Spanish and Vietnamese to Application Language Selection 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#217]
In addition to the English and Chinese, add Spanish and Vietnamese 
![Screen Shot 2021-02-16 at 3 59 45 PM](https://user-images.githubusercontent.com/3453407/108146729-b1ca5080-709b-11eb-929c-914de00262a4.png)

**Comment by jaredcwhite** [comment]
Somehow this got missed in the merge from upstream master. Fixing in my upcoming PR.

**Comment by kathyccheng** [comment]
Looks good, closed in #229
