### ISSUE TITLE
Update <Region> to Hayward 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#222]
1. Contact 
2. Household Member
3.  Preferences

On the contact information screen, 
Do you work in <Region> should be 
Do you work in City of Hayward? 

![Screen Shot 2021-02-16 at 10.38.40 PM.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/d105c557-0497-41f4-9efc-41fbeb3a4e36)

On the household member screen, 
Do they work in <Region> should be
Do they work in the City of Hayward? 

![Screen Shot 2021-02-16 at 3.44.54 PM.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/bf7419d3-e92f-4096-bd41-40ae1523ce8b)

On preferences screen, should be 
Live in City of Hayward Preference
Work in City of Hayward Preference
![Screen Shot 2021-02-16 at 3 46 08 PM](https://user-images.githubusercontent.com/3453407/108166566-5e1f2d80-70c2-11eb-96a0-a9a5566fecc5.png)

**Comment by jaredcwhite** [comment]
Please confirm and close issue if this is done.

**Comment by kathyccheng** [comment]
Looks good, closed in #229
