### ISSUE TITLE
SoHay Application Live Work Preference Descriptions 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#225]
SoHay Application Screen for Live Work Preferences, the live and work preferences are missing descriptions 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/faa654c7-d2ab-43d3-babd-f4c7aa496597)

Live in City of Hayward Preference
At least one member of my household lives in the City of Hayward.

Work in City of Hayward Preference
At least one member of my household works or has been offered work in the City of Hayward.

**Comment by jaredcwhite** [comment]
Please confirm and close issue if this is done.

**Comment by kathyccheng** [comment]
Looks good, closed in #229
