### ISSUE TITLE
Add descriptions for 2 displacement preferences 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#226]
Add descriptions for the displacement preferences 
Fix the title for the Mission Corridor displacement preference

Displacee Tenant Housing Preference
At least one member of my household was displaced from a residential property due to redevelopment activity by the Hayward Housing Authority, the Redevelopment Agency or the City of Hayward.

Mission Boulevard Corridor (SR 238) Displacee Tenant Housing Preference
At least one member of my household is an SR 238 Program Participant as required under the terms of the SR 238 Settlement Implementation Project. Program Participants are tenants of previously sold Caltrans properties along the SR 238 Mission Boulevard Corridor and are given occupancy preference when new below-market housing is constructed in the Corridor.

https://www.hayward-ca.gov/238/background

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/2cd74dd1-d8 16-4009-b09f-3d144236aa97)

**Comment by jaredcwhite** [comment]
@kathyccheng I'm working on a PR to encompass this and the other related translation issues.

**Comment by kathyccheng** [comment]
Looks good, closed in #229
