### ISSUE TITLE
[Hold] SMC: Townhouse Suites Listing with MidPen

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#239]
Listings Spreadsheet 
https://docs.google.com/spreadsheets/d/11Q5VlFbr1YXG3MeWl22k7UWif-LG73CQxQW5xk2EpFc/edit#gid=1787912937

**Comment by netrabadami** [comment]
@kathyccheng  whats the work on this? should i be preparing the listing Json from from spreadsheet and import the listing?

**Comment by kathyccheng** [comment]
Yep @netrabadami you'll want to set up the JSON and then import the listing. We'll want to take a look on staging first. You might want to sync with @software-project on his efforts to catch up SMC to the new schema before prepping the JSOn

**Comment by netrabadami** [comment]
Thanks @kathyccheng 
@software-project can we sync on this please.

**Comment by netrabadami** [comment]
@kathyccheng do we know if the listing spreadsheet is complete? i can see few values missing. 
For Example: 
1. Under Units section - Square Footage value is "varies" i believe we either need number or range 
2. Under Units section - Floor value is  "all" - what does this mean?
3. Under Waitlist & Lottery (Availability) - Available Units are "45" - how many of them are studios? 1 Bedrooms? 2 Bedrooms?

**Comment by vubang228** [comment]
@netrabadami I updated the spreadsheet to answer your questions for number 1 and 2. For the available units, we won't know that until later. Do you have enough now to create the first draft of the listing?

**Comment by netrabadami** [comment]
@vubang228 Thank you for the updates. 
 Few details are still missing e.g Application Due date , Leasing Agent Phone etc. Also i believe we can have dummy data in place.

I have the draft listing ready with the available data. i have added 45 units (27 studio, 15 one Bedroom, 3 Two Bedrooms) it can be updated once we have accurate number of units.

**Comment by vubang228** [comment]
@netrabadami we typically have them provide us 70% of the spreadsheet filled out, then we complete the draft listing to send to them to review. Then the remaining 30% is completed and we get the final listing ready. Do you think we're ready to show them this draft listing for this next step? @kathyccheng as well?

**Comment by kathyccheng** [comment]
@vubang228 we have to get the SMC environments set up first and then catch them up with the updates from Alameda first. once that's done, targeting this week, we can push the listing up to staging.

**Comment by kathyccheng** [comment]
@software-project can you see where we're at with this and then push up to staging once SMC is caught up?

**Comment by kathyccheng** [comment]
Closing because we're no longer doing this
