### ISSUE TITLE
Sohay Lottery Results 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#255]
Add SoHay Lottery Results
Download Results should link to URL below: 
https://org-housingbayarea-public-assets.s3-us-west-1.amazonaws.com/SoHay_Lottery_Results_Hayward_Final.pdf

See original issue 
https://github.com/bloom-housing/bloom/issues/987

![image](https://user-images.githubusercontent.com/3453407/114812186-7d160500-9d7d-11eb-875a-ee186bdaffe5.png)

**Comment by kathyccheng** [comment]
@pbn4 can you help update the Download Results for SoHay to this URL and push this update live on Alameda?

**Comment by pbn4** [comment]
Done
