### ISSUE TITLE
[Alameda] Aurora Listing by Affirmed in Oakland 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#265]
This is a listing, like Nova with no application, it'll use that referral component. And it's al 30% of income. 

Full LIsting Spreadsheet: 
https://docs.google.com/spreadsheets/d/1qGNsJ6U1a12LsY9PMaz_VwpCLPJrYm5zHye2X1mnCmk/edit#gid=1787912937

**Comment by emilyjablonski** [comment]
Preliminary listing data & image for this has been merged, waiting on some data feedback in the spreadsheet to continue (need # units and AMI information)
