### ISSUE TITLE
Last City Center Updates 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#299]
Spreadsheet in yellow: 
https://docs.google.com/spreadsheets/d/1T4Ha4sub7fQjYS_9LB2QtYDbOMaSZ7X9yqxbYQDVd7M/edit#gid=1804508109

* Turn waitlist size back off (I'm sorry @software-project!) 
* Update application deadline date, hopefully final date

**Comment by software-project** [comment]
@kathyccheng I think we can close this one, right?

**Comment by kathyccheng** [comment]
Yep!
