### ISSUE TITLE
[Alameda] Jordan Court Listing with SAHA

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#337]
Listing Spreadsheet: 
https://docs.google.com/spreadsheets/d/1-M386fCqfexw-uT1JKbs_zWJhZuAVdEyV0Zg11wVPhY/edit#gid=1787912937

**Comment by software-project** [comment]
@kathyccheng I think the link to spreadsheet is wrong. It looks like Mercy.

**Comment by kathyccheng** [comment]
@software-project oops! updated

**Comment by kathyccheng** [comment]
@software-project next round of Jordan Court updates are ready in the QA tab here: 
https://docs.google.com/spreadsheets/d/1-M386fCqfexw-uT1JKbs_zWJhZuAVdEyV0Zg11wVPhY/edit#gid=1804508109

**Comment by kathyccheng** [comment]
@software-project here is what the Jordan Court Berkeley Housing Authority preference should look like: 

![image](https://user-images.githubusercontent.com/3453407/125311809-b2d97400-e301-11eb-8bf7-950b3b8abf7d.png)

Title: Berkeley Housing Authority
Description (LIsting Detail Page): Project-based voucher units funded by the Berkeley Housing Authority

Application Page in Preferences 
Select Text: Please indicate if you are interested in applying for one of these apartments
Title: Berkeley Housing Authority Apartments
Description: These apartments have a monthly rent that is approximately 30% of household income. I understand I must also qualify through the Berkeley Housing Authority’s requirements for this unit and that there will be both a screening process with SAHA and an additional application process through the Berkeley Housing Authority.

Sub-Preference: Berkeley Housing Authority Project Based Voucher Section 8 apartments
Read More for Sub-Preference: The minimum monthly income is $0. The maximum monthly income is $3,995 for 1 person or $4,566 for 2 persons. The maximum annual income is $47,950 for 1 person or $54,800 for 2 persons.

**Comment by kathyccheng** [comment]
@software-project here is another round of QA updates for Jordan Court 

https://docs.google.com/spreadsheets/d/1-M386fCqfexw-uT1JKbs_zWJhZuAVdEyV0Zg11wVPhY/edit#gid=1804508109

**Comment by kathyccheng** [comment]
Slew of Final items captured in #356

**Comment by kathyccheng** [comment]
Closing this original one
