### ISSUE TITLE
Corsair Flats listing page resulting in 404 error in IE11

### ISSUE THREAD

**Issue by jacchau** [housingbayarea/bloom#35]
Alameda: Check corsair flat listing on IE 10 and 11.

Note: Eden Housing is reporting that there is an issue with visiting the Corsair Landing listing on browser stack and it was giving an error after clicking 'See Details' on the browse property page.

**Comment by jacchau** [comment]
I checked this on browserstack for Windows 10 and 11 and seems to validate that there is a bug when using IE (11)

**Comment by jaredcwhite** [comment]
@jacchau There's a slew of things that need to get polyfilled and possibly changed in order to support IE via React. Is that still a requirement at this point in time? I know in some demographics IE usage stats are extremely low.

**Comment by jacchau** [comment]
Got it, thanks for the clarification @jaredcwhite - seems like this is a known issue. Let's icebox this for now. Looking at GA for SJ and SMC DAHLIA, seems that 8-10% are from IE (6-8%) and Edge (~2%).

**Comment by jaredcwhite** [comment]
Sounds good. Obviously we should strive to support all browsers generally, but IE in particular is so old and deprecated by now and only getting harder to deal with as time goes on.

**Comment by bk3c** [comment]
Sorry I'm late to the party on this, but my understanding is that IE11 is still a requirement, in part because it's what's still installed on a lot of SF city-owned computers. I'm going to file a bloom core issue for that, and then we can figure out what the priority needs to be.

**Comment by bk3c** [comment]
Closing this in favor of the Bloom core issue, since this isn't really a jurisdiction-specific issue at this point.
