### ISSUE TITLE
Starling - Eden - Customizations 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#367]
**Customizations Needed** 
* Are there any new preferences? 
  *  Live or Work in City of Alameda 

Add new preference to the list: 

Title: Live or Work in the City of Alameda 
Description (Listing Page): At least one member of my household lives or works in the City of Alameda 
Live Description: At least one member of my household lives in the City of Alameda 
Work Description: At least one member of my household works in the City of Alameda

**Comment by seanmalbert** [comment]
This is up and assigned to Starling Eden - https://partners.housingbayarea.org/listings/82199cf6-bb64-471b-8498-6f1c258af3e2

**Comment by kathyccheng** [comment]
@seanmalbert preference on listing looks good! here are some issues on the application management side 

1. Claimed Live/Work in the CITY of Alameda preference doesn't show up in the application summary 

It looks like it's saving okay in the database, but I can't fully interpret the preference storage 
Here's my test application for testing: confirmation number: f7f58e4e-3554-420d-a28e-035dae348b3d, listingid: 9718c89c-36b8-4147-a9d5-e2446a70c250

https://share.getcloudapp.com/o0uP5Glj


2. Live/Work in CITY of Alameda preference doesn't show up in the CSV export 
![image](https://user-images.githubusercontent.com/3453407/135659862-4d89a8a9-6773-43cb-9973-a8956665ae7c.png)

**Comment by kathyccheng** [comment]
@seanmalbert updated office hours language: 
Monday-Friday 10 am to 4pm. Please call the leasing office at 510-499-2491 to schedule an appointment during office hours. Persons with disabilities have the right to request reasonable accommodations. Reasonable Accommodations will be submitted to the 504 Coordinator for Eden Housing by phone (510) 697-6310; TTY number 1-(800) 735-2922, by fax at (510) 372-0617 or email at leaseup@edenhousing.org.

**Comment by kathyccheng** [comment]
Closing, live
