### ISSUE TITLE
Alameda - Missing Translations + Filipino

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#393]
**Notes**
* Add translations for Alameda County for the new homepage, how it works, what to expect work that Jared's been doing 
* Whoever gets here first also probably needs to add Filipino to Alameda languages 
* I also realized that the application translation updates were actually done in Core, so you might need to separate out an issue for that 

[Spanish](https://docs.google.com/document/d/1B53lsXGeZdlRWI_WMZXSjHLBqC--TCnT/edit)
[Vietnamese](https://docs.google.com/document/d/1oLgqEJeaRxzxFPRNHWmUxY74xk0yvVFv/edit)
[Chinese](https://docs.google.com/document/d/1zHE4JmpUe2Yy8D1NkyZ4sap_JHr6EcC_/edit)
[Filipino](https://docs.google.com/document/d/12vBH11TI_hY6-MX2baUy5S_jHaOeCNuo/edit)

This was the English page for reference: https://docs.google.com/document/d/1czPz_CgcnoaIBq19CofHFFlKgoXptzhho1SbNcteOMw/edit#heading=h.ic9u69uba1zz

This was the bulk of Jared's new work: https://github.com/housingbayarea/bloom/pull/389

### Tech Notes

@jaredcwhite: I'll work on a PR first for the homepage/how it works stuff + application step updates in existing en/es/vi/zh languages. Then I'll review what got done in https://github.com/bloom-housing/bloom/pull/2728 and look at seeing up a second Alameda PR for adding the extra Filipino translations and configuring the language in Next.js.

**Update:** it looks like the final Confirmation step was updated in Core directly, so I filed a separate Core issue/PR to add translations for that step: https://github.com/bloom-housing/bloom/issues/2734

~~**2nd Update:** Probably makes sense to tackle #395 as part of this.~~

**Comment by jaredcwhite** [comment]
FYI, it looks like Alameda still has its own updated design for the What to Expect step & Terms step in the application forms flow, so I'll just update that here rather than core.

**Comment by jaredcwhite** [comment]
I discovered that the work in Core for https://github.com/bloom-housing/bloom/pull/2558 isn't yet in Alameda, so I'm not sure exactly what the sequence of events should be here. Merge that code in now? Or wait and merge it in part of the added translations work captured in bloom-housing/bloom#2734?

**Comment by jaredcwhite** [comment]
Seems like the best idea is to tackle this all at once, so I'll finish up this issue and the https://github.com/bloom-housing/bloom/issues/2734 stuff, and then see if we can try to roll everything out at once.

**Comment by kathyccheng** [comment]
@jaredcwhite wasn't quite sure where to put this but here's translations for the button 

Read About How It Works 
Spanish: Lea acerca de cómo funciona
Vietnamese: Đọc về cách nó hoạt động
Chinese: 閱讀它是如何工作的
Filipino: Basahin ang Tungkol sa Paano Ito Gumagana

**Comment by seanmalbert** [comment]
@kathyccheng ,
This should be ready for QA at https://ala.bloom.exygy.dev

**Comment by kathyccheng** [comment]
Closing this one, updates captured in new issues
