### ISSUE TITLE
Alameda - additional copy in application confirmation page

### ISSUE THREAD

**Issue by jaredcwhite** [housingbayarea/bloom#395]
This is to re-add the "Prepare for Next Steps" section which we didn't want in core. https://github.com/bloom-housing/bloom/issues/2510

**Comment by jaredcwhite** [comment]
@kathyccheng @slowbot Can you remind me what where this link should go again? There was language we left off of the confirmation page we were planning to add back in just for Alameda, but I'm not sure what it would point to.

> Prepare for next steps
> 
> While you wait, there are things you can do to prepare for potential next steps and future opportunities. 
> Read about how you can prepare for next steps (link)

reference: https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=1163%3A8735

**Comment by kathyccheng** [comment]
@jaredcwhite it should go to the Get Prepared for Placement section on the How to Apply page

**Comment by kathyccheng** [comment]
LGTM!
