### ISSUE TITLE
Update Alameda County Portal Content (ongoing)

### ISSUE THREAD

**Issue by jacchau** [housingbayarea/bloom#4]
**Summary:** Update Alameda County Portal with Alameda specific content from the following content library https://docs.google.com/spreadsheets/d/1QZxvZLjunXoYV9leejKDZbBHQJ3M8gnGIlAVajPnPuM/edit#gid=85678091.

**Comment by antonelitum** [comment]
I just changed the content for Disclaimer and Privacy policy as it might the following link: https://www.acgov.org/government/legal.htm
If we have the capacity, please let's add this, otherwise, we can wait until we receive final confirmation.

**Comment by jacchau** [comment]
Thanks @antonelitum. @jaredcwhite, summarized updates below - please expect for another round of finalization after this update:

1. Remove Header Feedback and Footer Menu URL to old SMC Survey to blank (placeholder)
2. Link Footer Menu 3 Disclaimer to https://www.acgov.org/government/legal.htm
3. Link Foot Menu 4 Privacy to https://www.acgov.org/government/legal.htm

**Comment by jacchau** [comment]
@jaredcwhite, FYI I updated the survey to an Alameda County specific one after @antonelitum 's confirmation that it was approved.

**Comment by jacchau** [comment]
2/24 Change log

**Updates to content library that needs to be updated on portal**

- Footer Contact 5 (link to San Mateo County Housing Portal)
- Footer Contact 6 (link to City of San José Housing Portal)

**Pending Confirmation from Alameda**

- Footer Contact 2 (Contact phone number)
- Footer Menu 2 (Contact email address)
- Main Menu 3 (Get Assistance external link)
- Privacy and Disclaimer

**Comment by jacchau** [comment]
3/2 Change log

**Updates to content library that are ready to be updated on portal**
Footer Contact 2 (Contact phone number)
Footer Menu 2 (Contact email address)

**Pending Confirmation from Alameda**
Main Menu 3 (Get Assistance external link)
Footer Menu 3 Privacy
Footer Menu 4 Disclaimer
Hero image

**Completed updates since last change log**

- Footer Contact 5 (link to San Mateo County Housing Portal)
- Footer Contact 6 (link to City of San José Housing Portal)
