### ISSUE TITLE
Alameda - City of Fremont Preference

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#400]
**Notes**
* Add a new preference in the jurisdiction of Alameda 
* The italicized text is what should go into the read more 

https://docs.google.com/document/d/1dSw8dNlG9q2wF9KV7aIPpUH9X-hG6MiY3UEhIBoT6ck/edit?usp=sharing

QA NOTES
Navigate to https://hba-partners-dev.netlify.app/ and verify that under alameda jurisdiction the new preference is available to add to a listing

Add preferences to a listing (either creating a new one or editing an existing one)

navigate to https://hba-public-dev.netlify.app/ and go through the application process for that listing, you should see the new preference and the application should save correctly

**Comment by sheneral** [comment]
Hmm I'm not seeing the preference on https://hba-partners-dev.netlify.app/ ? @YazeedLoonat

**Comment by sheneral** [comment]
Looks good!
