### ISSUE TITLE
SJ - New Resource

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#401]
**Acceptance Criteria**
* When I am on the SJ Resources page, then I expect to see the following design

**Notes**
* Move Bay Area Doorway Portals category up to the top of the page (currently it's on the bottom) 
* Update the description text underneath to include a new first sentence - including updating the translations
* Add one new resource for How It Works - there are translations for the text and also the link will change in each language

**Designs**
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=684%3A1518

**Copy + Translations**
https://docs.google.com/document/d/1DKBWrMe4vqKtqxcL6ADGCjHweLcOEelp18g-uPwgRg4/edit

**Comment by seanmalbert** [comment]
@sheneral , you can QA the resource updates on staging at https://sj.bloom.exygy.dev/additional-resources.

**Comment by sheneral** [comment]
Looks good!
