### ISSUE TITLE
Alameda - Update for South Alameda Preference

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#405]
**Notes**
* Add this description to the South Alameda preference - highlighted in yellow 

https://docs.google.com/document/d/15R_-W1dvl7_ZzxS0REQKvXLGvwCokskQDIV1pKEfUqQ/edit

**QA NOTES**
Head to https://hba-partners-dev.netlify.app/sign-in
add the South Alameda Preference to a listing

Head to https://hba-public-dev.netlify.app/
On the detail page for that listing, and verify that the new text is displayed for the south alameda preference, and verify that you can still apply to that listing with the preference without error

**Query to Execute**
```
UPDATE preferences
SET subtitle = 'At least one household member lives or works in Fremont, Newark or Union City.'
WHERE title = 'South Alameda County Region Housing Preferences'
```

**Comment by YazeedLoonat** [comment]
Hey @seanmalbert could you take a peek at this, I attached the query and made the change on hba-dev since this is all postgres no actual code

**Comment by sheneral** [comment]
Description is pulling in the question from the application process "Does anyone in your household satisfy..."

On public facing listing page: correct description is there in addition to the question
![Screen Shot 2022-05-16 at 11 56 02 AM](https://user-images.githubusercontent.com/100251192/168665296-f729b2d7-39fd-475e-9e67-d3645cef6d99.png)

On listing editor, description shows up as the question
![Screen Shot 2022-05-16 at 12 07 55 PM](https://user-images.githubusercontent.com/100251192/168665300-e7f68b26-93d0-4a0d-bb3c-dc767e3fe50a.png)

**Comment by sheneral** [comment]
Confirmed with Kathy, should have the description text wherever possible, and not the question "Does anyone in your household..." which is a question leftover from the paper application. 

Looks good!
