### ISSUE TITLE
SJ - Update Contact on Resources Page

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#408]
On San Jose Resources page, in the contact section update second paragraph of contact text to below: 

"For general program inquiries, you may call the Housing Department at 408-535-3860 or email sjhousingportal@sanjoseca.gov"

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/29e901d0-fd3a-4519-9411-99f24a7e9617)

**Comment by seanmalbert** [comment]
QA on https://sj.bloom.exygy.dev/

**Comment by sheneral** [comment]
Looks good!
