### ISSUE TITLE
Resource Format Update - Ala, SJ, SMC 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#409]
In each jurisdiction, update the format of the resources page to the new one we started in Detroit 

Notes
* Right now, big markdown file. In Detroit, we updated to actual component that imports the markdown files. Moves us closer to adding in cards via Partners. 
* Basic thing in Core and then more filled out 

QA notes for SMC: 
Start at the link below, look over the layout and each card in comparison to prod site to ensure there are no discrepancies
https://smc.bloom.exygy.dev/additional-resources
https://sj.bloom.exygy.dev/
https://ala.bloom.exygy.dev/

**Comment by sheneral** [comment]
Looks good
