### ISSUE TITLE
Alameda - City of Emeryville Preference

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#410]
https://docs.google.com/document/d/1_DZfjgwXkfK_vvIUCmNVyVaRG7aGv_9T4yHvG7u22hE/edit

**QA NOTES**
Head to https://hba-partners-dev.netlify.app/
verify that the new Emeryville preference is available to add to a listing
add the preference to a new or existing listing 

Head to https://hba-public-dev.netlify.app/
verify that the new preference is on the listing that you added it to on the previous step, and that the application form contains the new preference

**Comment by sheneral** [comment]
Not seeing the city of Emeryville preference on https://hba-partners-dev.netlify.app/? @YazeedLoonat 
![Screen Shot 2022-05-16 at 12 18 59 PM](https://user-images.githubusercontent.com/100251192/168666312-393a71ae-66a7-4750-a36e-db20532896e9.png)

**Comment by sheneral** [comment]
Looks good for the most part. There is no description for this one though, and we can get rid of the question also @YazeedLoonat -- confirmed with Kathy

![Screen Shot 2022-05-17 at 5.29.30 PM.png](https://images.zenhubusercontent.com/622f87292316976540c8d5bd/02b66557-658f-4ec6-9941-f80dc76c1774)

**Comment by YazeedLoonat** [comment]
@sheneral got this updated per your note if you would like to peep one more time please

**Comment by sheneral** [comment]
looks good on prod, closing
