### ISSUE TITLE
SJ Contact Translation Updates

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#420]
Translate via Google translate contact info at the right with phone number + email. Currently content updates missing in Spanish, Chinese, Vietnamese. Need to translate the whole paragraph. 

Text
For general program inquiries, you may call the Housing Department at [408-535-3860](tel:+1-408-535-3860) or email [sjhousingportal@sanjoseca.gov](mailto:sjhousingportal@sanjoseca.gov).

![image](https://user-images.githubusercontent.com/3453407/169880328-2f2d77a1-e6a5-4c1a-a462-4504c0bbb569.png)

**Spanish**:
Para consultas generales sobre el programa, puede llamar al Departamento de Vivienda al [408-535-3860](tel:+1-408-535-3860) o enviar un correo electrónico a sjhousingportal@sanjoseca.gov

**Chinese**:
對於一般計劃查詢，您可以致電房屋署 [408-535-3860](tel:+1-408-535-3860) 或發送電子郵件至 sjhousingportal@sanjoseca.gov

**Vietnamese**:
Đối với các thắc mắc chung về chương trình, bạn có thể gọi cho Bộ Gia cư theo số [408-535-3860](tel:+1-408-535-3860) hoặc gửi email tới sjhousingportal@sanjoseca.gov

QA Notes:
Start at the link below and notice different translations of contact info.
https://sj.bloom.exygy.dev/additional-resources

**Comment by sheneral** [comment]
@ColinBuyck Could you get to this this week?

**Comment by ColinBuyck** [comment]
Yep! I'll have it done before tomorrow's stand up.

**Comment by kathyccheng** [comment]
https://sj.bloom.exygy.dev/additional-resources

**Comment by sheneral** [comment]
looks good!
