### ISSUE TITLE
SMC Resource How it Works 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#421]
Placement of resource card: https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=1955%3A8875

- Add a "How it Works?" resource card on the RENTALS section as the first card
- Add title and description in English, Chinese, Spanish, & Vietnamese
- The title links to the corresponding PDF in the corresponding language

**PDFs in English, Chinese, Spanish, & Vietnamese**: 
Cloudinary Links to Host
* English: https://res.cloudinary.com/exygy/image/upload/v1656447895/Revised_Affordable_Housing_Application_and_Selection_Process_-_San_Mateo_County_Final_ENG_ydko9g.pdf
* Spanish: https://res.cloudinary.com/exygy/image/upload/v1656447890/Revised_Affordable_Housing_Application_and_Selection_Process_-_San_Mateo_County_ES_phyiwc.pdf
* Vietnamese: https://res.cloudinary.com/exygy/image/upload/v1656447899/Revised_Affordable_Housing_Application_and_Selection_Process_-_San_Mateo_County_VIET_ztpwj6.pdf
* Chinese: https://res.cloudinary.com/exygy/image/upload/v1656447884/Revised_Affordable_Housing_Application_and_Selection_Process_-_San_Mateo_County_CH_ntjioc.pdf

https://drive.google.com/drive/u/0/folders/1uAcMdHgtQu_4ovS09XLG8nn2eNk-ykV3

**Translations for Resource Card (highlighted in yellow)**
https://docs.google.com/document/d/1c77u4u2mKxlqAZQZrYF_eEIuWE_CIg-qcEibUPHPOpQ/edit#

**QA notes**
- Navigate to SMC resource page
- Make sure that the resource card shows up in all 4 languages
- Make sure the PDF is linked to the corresponding language

**Comment by sheneral** [comment]
LGTM
