### ISSUE TITLE
Alameda - New AMI Charts

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#427]
Add 2 New AMI Charts to Alameda County 
* Alameda County TCAC 2022 - https://docs.google.com/spreadsheets/d/1LOUWj_bqtCcGtRyq_jrr4aTYVJzmtzpItYVZVL0Yl3k/edit#gid=30284428
* Alameda County HUD 2022 - https://docs.google.com/spreadsheets/d/1LOUWj_bqtCcGtRyq_jrr4aTYVJzmtzpItYVZVL0Yl3k/edit#gid=657825290
* Bring over script from Detroit to make adding AMI charts easier, do this on hba dev and then merge up
* Just go to database, don't need to go through core, can just run it on hba

**QA NOTES**
head to the partner site https://hba-partners-dev.netlify.app/
go to create/edit a listing
add a unit
notice that the new ami charts are present, and the values match up with the expected values from the spreadsheets in the ticketo

verify that the listing can save properly
verify the listing detail page displays the correct ami info 

head to the public site https://hba-public-dev.netlify.app/
verify the public preview displays the correct info as well

**Comment by sheneral** [comment]
i know this is already in but looks good
