### ISSUE TITLE
Alameda - Application Terms Page Content + Translation Updates 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#432]
**Acceptance Criteria**
* The date should show the due date of the application, not the default text 
* The second bullet should change depending on the whether the listing is First Come First Serve or Lottery 

**Copy** 
English: This application must be submitted by [Date] 
Spanish: Esta solicitud deberá presentarse antes del [Date] 
Vietnamese: Đơn đăng ký này phải được nộp trước ngày [Date]
Chinese: 此申請必須於[Date]前提交
Filipino: Ang application na ito ay dapat isumite sa [Date] 

English: Eligible Applicants will be contacted by on a first come first serve basis until vacancies are filled 
Spanish: Los solicitantes elegibles serán contactados por orden de llegada hasta que se llenen las vacantes.
Vietnamese: Những người đăng ký đủ điều kiện sẽ được liên hệ trên cơ sở ai đến trước được phục vụ trước cho đến khi hết căn hộ trống.
Chinese: 合格申請人會依先到先得原則收到聯絡，直到補滿缺額。
Filipino: Ang mga kwalipikadong aplikante ay tatawagan sa pamamagitan ng first come first serve basis hanggang sa mapunan ang mga bakante. 

English: Eligible applicants will be contacted by the agent in lottery rank order until vacancies are filled. 
Spanish: Los solicitantes serán contactados por el agente de la propiedad en orden de clasificación hasta que se hayan llenado todas las vacantes.
Vietnamese: Các ứng viên sẽ được nhân viên đại diện bất động sản liên lạc theo thứ tự xếp hạng cho đến khi hết chỗ trống.
Chinese: 物業經紀人將按排名次序聯絡申請人，直到沒有空缺為止。
Filipino: Ang mga aplikante ay tatawagan ng ahente ng property sa ayon sa pagkakasunod-sunod ng rank hanggang sa mapunan ang mga bakante.

**Images** 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/788bc8d6-4096-42dc-b00b-ed563edbcfcb)

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/95799be2-4432-470f-8083-c8894ab68f3d
)

**Comment by jaredcwhite** [comment]
@YazeedLoonat On that date issue, can you confirm it's related to something related to the backend data? I'm pretty sure we're just formatting whatever's coming over the wire.

**Comment by kathyccheng** [comment]
@jaredcwhite the due date still looks to be fixed

**Comment by YazeedLoonat** [comment]
Hey @jaredcwhite I do think there is something wrong with the application due date that shows up on the `Terms` page of the `Review` step

if you have a listing with no application due date I think thats what is causing the issue here.

for example on: https://housing.acgov.org/listings

there are 2 listings, `Embark Apartments` has no application due date and the date that shows up on the term is in the 1900s, while `Doug Ford Senior Apartments` has an application due date and it shows up correctly

**Comment by jaredcwhite** [comment]
@YazeedLoonat OK, hmm, I suppose we've never actually supported applications without a due date for that particular form step.

@kathyccheng Maybe something we need to address first in core, or backport a fix from here?

**Comment by kathyccheng** [comment]
Ah this is a great catch guys!! I'll create a new issue to handle it but yeah I think we should probably remove that first sentence and probably first bullet for no application due date listings
