### ISSUE TITLE
Alameda - Get Assistance Page Missing Translations 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#433]
**Acceptance Criteria** 
* When I am on the Get Assistance Page, the 2 new sections - How to Apply and Additional housing opportunities and resources - need translations in each language - Spanish, Vietnamese, Chinese, Filipino 
* When I am on the Get Assistance Page in Vietnamese, then I don't see the contact information on the side 

**Copy** 
English: How to apply to affordable housing
Spanish: Cómo solicitar una vivienda asequible
Vietnamese: Làm thế nào để đăng ký nhà ở giá cả phải chăng
Chinese: 如何申請經濟適用房
Filipino: Paano mag-apply sa abot-kayang pabahay

English: You can find and apply for affordable rental opportunities.
Spanish: Puede encontrar y solicitar oportunidades de alquiler asequibles.
Vietnamese: Bạn có thể tìm và đăng ký các cơ hội cho thuê với giá cả phải chăng.
Chinese: 您可以找到併申請負擔得起的租賃機會。
Filipino: Maaari kang maghanap at mag-aplay para sa abot-kayang pagkakataon sa pag-upa.

English: Read about how it works 
Spanish: Lea acerca de cómo funciona
Vietnamese: Đọc về cách nó hoạt động
Chinese: 了解它是如何工作的
Filipino: Basahin ang tungkol sa kung paano ito gumagana

English: Additional housing opportunities and resources
Spanish: Oportunidades adicionales de vivienda
Vietnamese: Các Cơ hội Nhà ở Bổ sung
Chinese: 其他住房機會
Filipino: Karagdagang Mga Oportunidad at Mapagkukunan ng Pabahay

English: We encourage you to browse other affordable housing resources.
Spanish: Le invitamos a consultar otros recursos de vivienda de precio accesible.
Vietnamese: Chúng tôi khuyến khích quý vị xem các nguồn thông tin trợ giúp về nhà ở giá phải chăng khác.
Chinese: 我們建議您瀏覽其他可負擔房屋資源。
Filipino: Hinihikayat ka naming mag-browse ng iba pang mapagkukunan ng abot-kayang pabahay

English: View opportunities and resources
Spanish: Ver oportunidades y recursos
Vietnamese: Xem các cơ hội và nguồn lực
Chinese: 查看機會及資源
Filipino: Tingnan ang mga pagkakataon at mapagkukunan

English: Contact
Filipino: Makipag-ugnayan

English: For listing and application questions, please contact the Property Agent displayed on the listing.
Filipino: Para sa mga tanong sa listahan at aplikasyon, mangyaring makipag-ugnayan sa Ahente ng Ari-arian na ipinapakita sa listahan.

**Images**
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/2ba6ab2a-21d6-418e-a241-8d3961970b67
)

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/eb5820ce-e72c-4462-87ac-5d0b057d91ec)

**Comment by jaredcwhite** [comment]
The contact info is the same one as the Resources page, so we can tackle that within that batch of work (but I'll make it default to English in the meantime).  Regarding those two content sections, I think I'll need the translations for those. Didn't see them in existing materials.
