### ISSUE TITLE
SJ - New AMI Charts

### ISSUE THREAD

**Issue by sheneral** [housingbayarea/bloom#446]
Need to add 2 new AMI charts to SJ

San Jose HCD Income Limits 2022: https://docs.google.com/spreadsheets/d/1LOUWj_bqtCcGtRyq_jrr4aTYVJzmtzpItYVZVL0Yl3k/edit#gid=1991387615

San Jose HUD/HOME 2022:
https://docs.google.com/spreadsheets/d/1LOUWj_bqtCcGtRyq_jrr4aTYVJzmtzpItYVZVL0Yl3k/edit#gid=1795921255

**Comment by kathyccheng** [comment]
LGTM
