### ISSUE TITLE
Add "Oakland Housing Authority: details on the "Housing Authorities in Alameda County"

### ISSUE THREAD

**Issue by antonelitum** [housingbayarea/bloom#45]
On the Section "Housing Authorities in Alameda County" please add	

Resource Card 5 Header: Oakland Housing Authority	
Resource Card 5 Link: http://www.oakha.org/Pages/default.aspx

**Comment by antonelitum** [comment]
@jaredcwhite it would be good if you can complete this during the next sprint

**Comment by jaredcwhite** [comment]
@antonelitum Oh you know what, I included it along with the Skylyne updates we're wrapping up, and I forgot to make a note of it here. So that's already ready to roll.

**Comment by antonelitum** [comment]
@bk3c let me know when this change will be live Rebecca asked me about it again, today. thanks!

**Comment by bk3c** [comment]
This looks like it went live with #56 this morning. @antonelitum, if you can confirm that everything looks right with Rebecca then feel free to close this.

**Comment by bk3c** [comment]
Closing for lack of complaints.
