### ISSUE TITLE
SMC - Update TCAC 2022 AMI Table Label

### ISSUE THREAD

**Issue by sheneral** [housingbayarea/bloom#451]
Let's update the TCAC 2022 AMI chart to say "San Mateo County TCAC 2022"

![Screen Shot 2022-07-06 at 4.26.21 PM.png](https://images.zenhubusercontent.com/622f87292316976540c8d5bd/049e9b9d-9c93-4045-b6c4-ca15d1f0bc86)

**Comment by seanmalbert** [comment]
This can be reviewed on https://partners.housingbayarea.org/

**Comment by sheneral** [comment]
LGTM
