### ISSUE TITLE
SMC - change footer contact email 

### ISSUE THREAD

**Issue by sheneral** [housingbayarea/bloom#454]
The contact email in the [footer](https://smc.housingbayarea.org/ ) currently has housing@smchousing.org as the mailto address

Let's change it to doorway@smchousing.org, per our SMC stakeholders 

QA Notes:
Start here: https://smc.bloom.exygy.dev/
1. Scroll down to contact button in footer
2. Verify that it leads to the updated address above.

**Comment by kathyccheng** [comment]
LGTM
