### ISSUE TITLE
Add the new listing: Greystar Skylyne Listing

### ISSUE THREAD

**Issue by antonelitum** [housingbayarea/bloom#46]
This is the link to the developer' listing information: https://docs.google.com/spreadsheets/d/1KoWC9fb9hKoBuwUCZ80rod4qcjbT70l4dO1y2Lr0szg/edit#gid=0

80% of the details are completed, they should be done by tomorrow.
It would be great if we can start sharing it with them so they can see how it is display and help us with QA.

The will be done by tomorrow and they want to publish it on Friday or by Monday

**Comment by jaredcwhite** [comment]
@antonelitum First draft is up now for QA:

https://5ebc6bb3e75fad81c93f5144--wonderful-joliot-c00737.netlify.app/listing/q3h9p31e

**Comment by antonelitum** [comment]
@jaredcwhite wonderful, looking great! Thank you!
We started the review QA process with the developers. I created QA Sheet in the same [Listing spreadsheet](https://docs.google.com/spreadsheets/d/1KoWC9fb9hKoBuwUCZ80rod4qcjbT70l4dO1y2Lr0szg/edit#gid=943789941) so you can see any changes that it might be needed, column D "Currently it says", column E "It should say"
Let me know if you have preferences or suggestions on how to track the potential changes. thanks!

**Comment by jaredcwhite** [comment]
@antonelitum That sounds good. For the sake of sanity I won't push any requested changes until you let me know when they've finished the QA—other than I do want to get the Units data in here shortly.

**Comment by antonelitum** [comment]
@jaredcwhite Make sense, I'll keep you posted on when QA is done.
Regrading Unit data, what do you mean by Unit data? the whole “Units Available” section is filled out.

**Comment by jaredcwhite** [comment]
@antonelitum Oh I meant the unit summaries — it's updated now so the Studio, 1BR, and 2BR data should all be in place. New URL:
https://5ebde47ea7dc2e00061f5852--wonderful-joliot-c00737.netlify.app/listing/q3h9p31e

**Comment by jaredcwhite** [comment]
@antonelitum Another update of QA improvements:
https://5ebecb3b9841f90006100015--wonderful-joliot-c00737.netlify.app/listing/q3h9p31e

**Comment by bk3c** [comment]
Released to production this morning based on everything up to and including #56.
