### ISSUE TITLE
SJ - Add link in How it Works 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#467]
Add link to "visit the affordable housing portal" to the listings page 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/1155e023-7229-4c68-8569-16cf31d96e2f)

**Comment by emilyjablonski** [comment]
@kathyccheng what link is this / where does it go?

**Comment by kathyccheng** [comment]
@emilyjablonski that line in the screenshot "visit the affordable housing portal" should go to /listings on SJ

**Comment by emilyjablonski** [comment]
QA Notes: At the moment we don't have translations that include the separation of the newly linked string, so we cannot update this in other languages until we get those translations. The offline decision was to just add it in English right now.

Check out the how it works page and test out the new link.

**Comment by kathyccheng** [comment]
LGTM
