### ISSUE TITLE
SJ - What to Expect Overrides

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#491]
As a resident in SJ
I want to see translations for the What to Expect updates 

**Acceptance Criteria**
* When I am on the listings detail page What to expect, listings detail page banner, application get started, application terms, application confirmation and application confirmation email, then I will be able to see in English, Spanish, Chinese and Vietnamese 

**Notes**
* Add in translations for SJ only, not Core

**Translations**
https://docs.google.com/document/d/10ku7kavySUWP2gZRBoUrVsEHliNIkUck/edit

**Designs** 
https://www.figma.com/file/5fGM1vGvQCmnhLCDkuqROr/Public-What-to-Expect?node-id=16%3A4547

**Product Brief**
https://docs.google.com/document/d/1905UwGoceAskeNlEjRcIoShDMgENcnE6PXzxewECGro/edit#heading=h.jhuf99j9fm9

**Comment by jaredcwhite** [comment]
@kathyccheng I just noticed this—the Spanish text for the Terms and Confirmation is actually still English. Somehow the translations got missed there.

**Comment by jaredcwhite** [comment]
@kathyccheng At the bottom where it has the text "Applicants will be reviewed in the order received until all vacancies are filled" — I'm not sure where that's actually supposed to go. There's no string like that currently in the repo anywhere…?

**Comment by jaredcwhite** [comment]
@kathyccheng I'm actually struggling with the precise order of text for "What to Expect" on the listing page for each of the three cases and what is shown initially and what is behind the "read more" toggle. Can we reformat this so it just shows the exact order of text from top to bottom for Waitlist, Lottery, and FCFS?

**Comment by jaredcwhite** [comment]
Oh, and it also looks like the Spanish translation is still missing for "Eligible applicants will be placed on the waitlist on a first come first serve basis until waitlist spots are filled."

**Comment by kathyccheng** [comment]
@jaredcwhite noticing a few things off, this is for FCFS Vacant Unit 

**Confirmation Screen**
* Looks like the translations are all Spanish in Spanish, Vietnamese and Chinese 
![image](https://user-images.githubusercontent.com/3453407/198112434-b099e794-f6a2-4ba9-a2f6-30fd86bc743b.png)
![image](https://user-images.githubusercontent.com/3453407/198112491-2e84ef02-9ba9-4337-b632-d11be501f7da.png)


**Terms Screen**
*<br><br> showing up in all languages 
* Looks like we're missing Chinese and Vietnamese (they're all Spanish) 
![image](https://user-images.githubusercontent.com/3453407/198112701-4569af21-01c0-40b4-a117-783e3def5b33.png)
![image](https://user-images.githubusercontent.com/3453407/198112756-bdf32d0d-bc83-4b4d-a3be-1939851f8260.png)
![image](https://user-images.githubusercontent.com/3453407/198112801-70840090-dd0c-4a3c-b5cb-8abab184f66b.png)

**Comment by jaredcwhite** [comment]
@kathyccheng Ah, so for the Confirmation page there was a code-level issue that was making switching languages not work (why it stayed on Spanish). For terms, I actually did miss some strings. Working on a fix for both now.

**Comment by jaredcwhite** [comment]
@kathyccheng Sorry for the wait there, updated the PR so it should be showing the appropriate translated strings now.

**Comment by kathyccheng** [comment]
LGTM thanks @jaredcwhite!
