### ISSUE TITLE
HBA - Add GA4 tag 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#525]
As the jurisdictions in the bay, 
I want the public housing portals to have the latest analytics tracking
So that I can continue to analyze web traffic 

**Acceptance Criteria**
* When I am on every page on the SMC, SJ, or Ala public portals, then I should see the new GA4 tracking snippet in the head instead of the old one 
* When I go to the new GA4 property in each of the jurisdictions, then I should be able to see the new traffic 

**Notes**
* Snippets are commented below
* Do we have a staging environment set up for these?
* Can the old Google Analytics run at the same time as GA4? - this would be useful for testing

**On Implementation**
We'll need to update the config files for all of the sites in Netlify.

QA Notes:
https://smc.bloom.exygy.dev/
https://ala.bloom.exygy.dev/
https://sj.bloom.exygy.dev/

Open up google analytics and verify that visiting and interacting with these sites is reflected in both the old dev property along with the new GA4 one.

**Comment by iph-97** [comment]
**SMC**


<script async src="https://www.googletagmanager.com/gtag/js?id=G-CF6EGE0375"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-CF6EGE0375');
</script>

**SJ**


<script async src="https://www.googletagmanager.com/gtag/js?id=G-92LSKY0KHG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-92LSKY0KHG');
</script>

**AC**


<script async src="https://www.googletagmanager.com/gtag/js?id=G-DGGDV8CS3W"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DGGDV8CS3W');
</script>

**Comment by kathyccheng** [comment]
@sarahlazarich can you take a final look on all the production instances and just make sure it looks like it's been tracking data okay over the holiday break?

**Comment by sarahlazarich** [comment]
Looked over the production sites, and they were tracking data over the holidays. 

I wanted to note that GA4 counts users different than UA, so the user counts do not match between the two. Izzie sent [this](https://support.google.com/analytics/answer/11986666?hl=en#zippy=%2Cin-this-article) over, which indicates that GA4 uses the term "Users" to refer to the total number of unique users who logged an event, and UA uses "Users" to refer to just the number of users in general (not unique). Doesn't seem like this would be a cause for concern, but wanted to call it out.
