### ISSUE TITLE
SJ - Update Resource Content 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#527]
**Acceptance Criteria** 
* When I'm on the resources page in SJ only, I want to see the following resources updated 

**Content**
https://drive.google.com/file/u/1/d/19dDZ7CKyY2E8o0u9ZvoJ1tiAKrPmpDxc/view?usp=docs_web

**Comment by kathyccheng** [comment]
FYI: https://github.com/housingbayarea/bloom/pull/462

**Comment by emilyjablonski** [comment]
QA Notes:
https://sj.bloom.exygy.dev/additional-resources
Ensure the card text matches the changes requested in the issue.

**Comment by sarahlazarich** [comment]
Looks good to me - this passed QA on https://sj.bloom.exygy.dev/additional-resources
