### ISSUE TITLE
Public User not able to be verified

### ISSUE THREAD

**Issue by YazeedLoonat** [housingbayarea/bloom#566]
**Describe the bug**
There was an issue where when a user is trying to confirm their account on the public site, they were running into a problem where there account was never getting confirmed. This meant that they were never logging in even though they clicked the confirmation link on the email.

**To Reproduce**
1. Go to public site (using the deploy preview in the pr, or dev, staging make this easier to verify)
2. create a new user
3. go to confirm that account
4. notice that nothing happens, your new user is not confirmed

**Expected behavior**
User should be confirmed when they click on the confirm account link in the email

**Comment by sarahlazarich** [comment]
QA'd this at new link: https://ala.bloom.exygy.dev/

Was able to confirm my account - this passed QA!

![Screenshot 2023-01-05 at 5 26 10 PM](https://user-images.githubusercontent.com/118844176/210899388-7158bf6a-a609-417c-a255-be01413c31d3.png)
