### ISSUE TITLE
Referral Application Section Not Showing on Public

### ISSUE THREAD

**Issue by ColinBuyck** [housingbayarea/bloom#577]
**Describe the bug**
After selecting that a listing is a referral opportunity on the partner's side, the section still doesn't show up on the public side. 

**Technical Context**
It is checking for listing.referralApplication which doesn't seem to be on the listing object at all. Only piece related on the object is listing.referralOpportunity which is set to true in the case described above.

**Comment by KrissDrawing** [comment]
@ColinBuyck It seem to work fine for me 😃 Is that still a problem? 
After changing `is there a referral opportunity` to `yes` it displays this section:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/9580543/214068884-8c97b536-16f5-4c73-9698-5e72067fadd0.png">

**Comment by ColinBuyck** [comment]
@KrissDrawing Hmm it seems that my local setup has gotten out of sync in some way since I consistently reproduce this bug locally but I see it working now on hba and core's dev sites so I think this is handled. Thanks for the catch!
