### ISSUE TITLE
Add Equal Housing Opportunity logo + language

### ISSUE THREAD

**Issue by bk3c** [housingbayarea/bloom#58]
Companion issue to https://github.com/bloom-housing/bloom/issues/320, for Alameda and SMC specific implementations. Extra credit for getting it sorted for SJC as well.

**Comment by jaredcwhite** [comment]
@slowbot FYI, you can actually work on this directly here, it's not related to doing anything upstream in bloom-housing. But perhaps wait until we sort out #60 first.
