### ISSUE TITLE
SMC - Missing translations

### ISSUE THREAD

**Issue by sarahlazarich** [housingbayarea/bloom#582]
User Story:
As someone using the SMC Public Portal,
I would like the site to be translated in Spanish, Chinese, and Vietnamese
So that I can navigate the website in the language of my choice.

Additional Notes:

Remedy the missing translations found in this doc [San Mateo Translations](https://docs.google.com/spreadsheets/d/1m03_FKvozZ6GC_PsRUuX1mINtUXdAkoiUpxLWVQ3On4/edit#gid=1003536471)
AC:

The translations listed in the sheet are updated in Spanish, Chinese, and Vietnamese.

**QA Notes**
Translations should appear in all places plus the confirmation email.
URL: https://smc.bloom.exygy.dev/

**Comment by KrissDrawing** [comment]
@sarahlazarich  We're not using `region.short` on page. Is there a reason for that to exist in translations document? At first glance it looks similar to `footer.copyRight`, which we have with copyright sign.

**Comment by sarahlazarich** [comment]
@KrissDrawing -- I believe I confused it with the text in the footer. Can we make sure that the footer.copyright is translated?

As to why this was in the document, @ColinBuyck found several instances when we were going through this initially where overrides were captured in the script output, or some strings were removed from the page but not cleaned up and showed up in the output because of that. I'm thinking this is one of those cases, but Colin can correct me if I'm wrong.

**Comment by ColinBuyck** [comment]
That is correct @sarahlazarich! (cc: @KrissDrawing)

**Comment by sarahlazarich** [comment]
this looks good!!
