### ISSUE TITLE
Alameda - Missing Translations

### ISSUE THREAD

**Issue by sarahlazarich** [housingbayarea/bloom#584]
As someone using the Alameda Public Portal,
I would like the site to be translated in Spanish, Chinese, Filipino, and Vietnamese
So that I can navigate the website in the language of my choice.

Additional Notes:

Remedy the missing translations listed here: [Alameda Translations](https://docs.google.com/spreadsheets/d/1LCqLN_8cJ_SROm7QjpxhvgzNx3hv3PdUI9W8w9pN23M/edit?userstoinvite=isabelle.hirschy%40exygy.com#gid=601677761)

AC: The translations listed in the sheet are updated in Spanish, Chinese, Filipino and Vietnamese.

**Comment by KrissDrawing** [comment]
@sarahlazarich I don't have access to that translations document.

**Comment by sarahlazarich** [comment]
@KrissDrawing  you should be good to go now

**Comment by sarahlazarich** [comment]
All the translations listed in this doc are good to go --- however, I noticed that there are some phrases in the confirmation email (below) that are untranslated and also weren't in the doc. I will open a separate ticket for that. ![Screenshot 2023-03-08 at 12.31.13 PM.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/73ac5f46-2c6e-4ae8-8ed4-9b1844d2bdb6)
