### ISSUE TITLE
HMI Chart Only Limited By Max Occupancy

### ISSUE THREAD

**Issue by ColinBuyck** [housingbayarea/bloom#586]
**Describe the bug**
When a listing contains a minimum occupancy value above 1 for all units, the HMI chart still shows household sizes of 1 to the max occupancy.

**To Reproduce**
1. Create a new listing with a single unit
2. Set the minimum occupancy to 3 and the max to 5
3. Select an AMI chart and Percentage
4. Save and publish
5. View the listing on the public side and notice that the HMI chart displays household sizes below 3

**Expected behavior**
 Instead, the first row of the HMI chart should have a household size equivalent to the lowest minimum occupancy of all of the units associated with that listing.

**QA Notes**
In partners edit a listing to have a range of household size and make sure the appropriate table appears on the public site for that listing. Make sure to test with multiple units having different values and also when the different units have different percentages (different headers and columns appear in that case)

**Comment by sarahlazarich** [comment]
QA'd at https://bloom.exygy.dev/ -- lgtm!
