### ISSUE TITLE
Internationalize the Alameda Footer

### ISSUE THREAD

**Issue by bk3c** [housingbayarea/bloom#60]
It appears that text strings for the Alameda footer are still hard-coded in `public-ala/components/AlamedaFooter.tsx`. With localization upcoming, we need to make sure everything is using translated strings from the JSON files.

For extra credit, align the footer approach between ALA, SMC, and SJ, whether or not we're going to split it out into its own component. I don't have a strong opinion one way or the other, but would prefer that everything works the same way unless there's a reason for it to be different.

Note: we also have https://github.com/bloom-housing/bloom/pull/326 in progress, which will end up being added to all three of the jurisdiction sites, so it may make sense to let that land first and then do all the jurisdiction-specific footer changes together. Not a firm dependency, though.

**Comment by bk3c** [comment]
See also #58.

**Comment by jaredcwhite** [comment]
@bk3c I think the only real difference is SMC and SJ just put the footer markup in the layout file, and ALA has it broken out into a separate file/component. Prob will just merge ALA back into the layout and use the SMC/SJ footers as a guide to use the translation strings.
