### ISSUE TITLE
Support Bug SMC - Application Dates Disabled Logic Inconsistent

### ISSUE THREAD

**Issue by ColinBuyck** [housingbayarea/bloom#600]
Prod Example: Pacific Oaks 
1. Create a new listing and mark as Open Waitlist rather than Available Units
2. Save the listing as draft
3. Editing again will show that “How is the application review order determined?” is hidden which blocks FCFS from being selected, and therefore, the “Is there an application due date?” question is hidden and the due date fields are disabled.
https://user-images.githubusercontent.com/53269332/228694093-6685577f-7b8d-4e43-a44c-8e77ed570202.mov

However
1. Create a new listing and then go to application process and enter the due date field
2. Save as draft
3. Edit the listing and mark as open waitlist
4. Save and listing will be both open waitlist and have date

https://user-images.githubusercontent.com/53269332/228695427-f72464fc-7e86-4eca-94fd-12851733a27b.mov

**Expected behavior**
Expected behavior here would be to keep the application due field enabled all the time, regardless of the waitlist type. We can remove the "Is there an application due date" question from the form.

**Comment by sarahlazarich** [comment]
Spoke with Design and Kathy, the ideal behavior here would be to keep the application due field enabled all the time, regardless of the waitlist type cc @ColinBuyck

**Comment by sarahlazarich** [comment]
Before this ticket gets picked up, we need to understand if the following ---
- Removing the "Is there an application due date?" question 
- leaving the dates enables all the time
have any downstream effects.

**Comment by sarahlazarich** [comment]
No downstream affects from either of the above questions, this is ok to pull in.

**Comment by sarahlazarich** [comment]
This looks good!
