### ISSUE TITLE
Support Related Bug - Partners Timeout Messaging

### ISSUE THREAD

**Issue by ColinBuyck** [housingbayarea/bloom#602]
There have been some reports of "disappearing edits" if a user doesn't save right away on an SMC listing. This has yet to be verified by Exygy team members but since this has come up a few times before and session timeouts can sometimes result in unexpected behavior, it is worth exploring better timeout messaging on partners.

**Comment by emilyjablonski** [comment]
Weren't able to reproduce this issue, didn't hear back from the reporter
