### ISSUE TITLE
Support Issue - AC user unable to submit application

### ISSUE THREAD

**Issue by sarahlazarich** [housingbayarea/bloom#606]
An applicant in Alameda County was  unable to submit their application and got an error message instead. We are unsure if this error is on our side or the users and need to investigate. The user reported that "I was in the process of submitting an application for housing for Dublin however coming to the agreement of terms, it states the following “ Looks like something went wrong. Please try again. Contact your housing department if you're still experiencing issues. ” I am not able to submit the application." 

The error on our side reads that `'preferences.0.options.2.key must be shorter than or equal to 128 characters'`

**QA NOTES**
Go to the partner's site and create a new preference with more than 128 characters as the title, and create an option for that preference with more than 128 characters as its title 

add that new preference to a listing

go to the public site and apply to that listing, making sure to select your new preference

the data should save successfully  

**Deployment Status**
this was deployed to both core, and hba

**Comment by sarahlazarich** [comment]
this looked good in dev!

**Comment by emilyjablonski** [comment]
Re-opening due to still having issues, context in [this Slack thread](https://exygy.slack.com/archives/C02G1S19QA2/p1681324073025109)

**Comment by emilyjablonski** [comment]
The remaining issue here was that we still have a max length validator on the key for extra data, so if a preference with a long option name collects an address, it could also prevent application submission. Here is an example error preventing folks from submitting `preferences.0.options.2.extraData.0.key must be shorter than or equal to 128 characters`.

I updated one of the Alameda staging listings to have this problem and you can see if you select the first preference and add an address, you are unable to submit and the same error is logged on `preferences.0.options.0.extraData.0.key`

**Comment by emilyjablonski** [comment]
New QA Notes: 
Adding this preference and selecting it and adding an address will cause the application submission to fail on main.
Option name: `At least one member of my household was required to relocate from current Dublin residence due to demolition of dwelling or conversation of dwelling from rental to for-sale unit (1 point)` and `Collect the applicant address`.
