### ISSUE TITLE
AC: Change email notifications from GovDelivery to Constant Contact

### ISSUE THREAD

**Issue by iph-97** [housingbayarea/bloom#608]
Alameda County has asked us to switch the email sign up link on the homepage notifications CTA from GovDelivery to Constant Contact. The new link is https://lp.constantcontactpages.com/su/q7wlZ9K. 

They will handle creating the email templates themselves, so Exygy is only responsible for updating the link. 

This is a medium priority request.

**Comment by emilyjablonski** [comment]
QA Notes: Ensure the `Sign up today` link on the [Alameda home page](https://housing.acgov.org/) goes to the new link above.

**Comment by sarahlazarich** [comment]
confirmed it does, thank you.
