### ISSUE TITLE
Doorway link in SMC/SJ/Ala footer

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#618]
When I am looking at footer on 
https://housing.acgov.org/
https://smc.housingbayarea.org/
https://housing.sanjoseca.gov/
Then I will see Doorway Housing Portal as the first link for additional Bay Area opportunities 
So that I can see that there is a regional portal 

**Details** 
* Add Doorway Housing Portal as first link on SJ, SMC and Ala production sites with line separator after
* Only Alameda has Filipino 

**Translations**
Doorway Housing Portal 
Spanish: Vivienda Portal de Doorway
Vietnamese: Cổng thông tin nhà ở của Doorway
Chinese: Doorway 房屋門戶
Filipino: Portal ng Pabahay ng Doorway

<img width="689" alt="image" src="https://github.com/housingbayarea/bloom/assets/3453407/1186882b-ebba-4b45-b529-f63546f04d79">

**Comment by sarahlazarich** [comment]
@KrissDrawing can you please pick up this ticket next? cc @ludtkemorgan

**Comment by sarahlazarich** [comment]
@KrissDrawing can you add QA notes here please? I'm not sure where to QA this.

**Comment by sarahlazarich** [comment]
QA'd at preview links!
