### ISSUE TITLE
Link back to Doorway if coming from Doorway 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#619]
When I come from Doorway, 
The I should see a URL param letting me know I'm coming from Doorway that should persist through the application 
When I hit the confirmation page after I submitted an application having come from Doorway 
Then I should see a different footer than "Browse more listings"
It should instead say "Browse more listings on the Doorway Housing Portal" 
So that I can go back to where I started my listings search from 

**Details**
* When a user comes to SJ, SMC or Ala from Doorway regional portal, then they should be directed back to Doorway to browse more listings
* Google Fellows will push URL param 

**Translations** 
English: Browse more listings on Doorway Housing Portal 
Spanish: Busque más listados en Doorway Housing Portal
Vietnamese: Duyệt thêm danh sách trên Cổng thông tin Nhà ở Doorway
Chinese: 在 Doorway Housing Portal 上瀏覽更多房源
Filipino: Mag-browse ng higit pang mga listahan sa Doorway Housing Portal

Design
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/1a6e6e37-dde2-4dbf-9b5a-3d35166bb152)

QA Notes
Start here: https://ala.bloom.exygy.dev/, https://smc.bloom.exygy.dev/, and https://sj.bloom.exygy.dev/

1. Find a listing using the common app and click apply online
2. When on the choose-language page, add "&source=dhp" to the url, and click enter
3. Then fill out the application and you will realize that the "Browse more listings" link on the confirmation page shows the updated language and redirects back to doorway.

4. Repeat this process on a different listing/application but without the appended doorway on the url
5.  You will notice that the confirmation page is unchanged compared to the current state of prod.

**Comment by ColinBuyck** [comment]
Yep @sarahlazarich! Will start poking around now 🖱️

**Comment by sarahlazarich** [comment]
I'm not seeing the updated language or redirect here when following the QA notes at https://bloom.exygy.dev/listings @ColinBuyck -- wondering what I might be missing?

**Comment by ludtkemorgan** [comment]
> I'm not seeing the updated language or redirect here when following the QA notes at https://bloom.exygy.dev/listings @ColinBuyck -- wondering what I might be missing?

@ColinBuyck you'll need to add the env variable to bloom.exygy.dev and retrigger the build

**Comment by sarahlazarich** [comment]
This looks good -- only off thing I noticed, sort of unrelated to the redirect, is the following screenshot. Is that just happening bc of the environment or is it related to this change @ColinBuyck 
![image.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/73c97040-f824-4fc6-8366-d94ba97dc48e)

**Comment by ColinBuyck** [comment]
@sarahlazarich That's unrelated to these changes and just a reflection of the preference data we have on HBA partners dev.

**Comment by sarahlazarich** [comment]
cool closing
