### ISSUE TITLE
Enable email notification sign up for SMC 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#630]
As a resident,
I want to be able to sign up to receive notifications when new listings are available 
So that I can be reminded to check the site and apply 

When I'm on the SMC homepage,
Then I'll see the component that will allow me to sign up
When I click sign up 
Then I'll see the gov delivery sign up page
When I'm on other languages
Then I'll see the sign up component translated 

**Details** 
* Link for the sign up: https://public.govdelivery.com/accounts/CASMATEO/subscriber/new?topic_id=CASMATEO_358%22%3eClick
* This might be set via an environment variable

**Design** 
Current SMC Homepage: 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/ccef7488-36de-4340-9743-008a8e6fb204)

Should mirror Alameda: 
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/d7f4f7a0-62fc-48ec-83d1-b189286910ac)

**Comment by ludtkemorgan** [comment]
@kathyccheng @sarahlazarich does SMC need any warning time before this is switched on? It is a config change in the db so I can do it at any time, but if we want to to give a longer warning period I can wait a few days to do it

**Comment by sarahlazarich** [comment]
@ludtkemorgan can we please do this EOW so they can prep?

**Comment by ludtkemorgan** [comment]
This is ready to review in the stage environment https://smc.bloom.exygy.dev/

**Comment by sarahlazarich** [comment]
this looks good!
