### ISSUE TITLE
Availability information can conflict with itself

### ISSUE THREAD

**Issue by trevorshannon** [housingbayarea/bloom#632]
**Describe the bug**
Property-level availability seems to be distinct from unit-level availability information, and they can conflict.

**To Reproduce**
1. Go to the [Casa Feliz](https://housing.sanjoseca.gov/listing/51bc9c3e-e896-4730-80d4-36420b995db9/casa_feliz_525_s_ninth_street_san_jose_ca) listing
2. Observe overall availability status as "Applications Closed" in the upper right
3. Scroll down to the unit details
4. Observe Studio availability for both 30% and 35% AMI as "Waitlist Open"

A similar conflict can be seen in the [Gish Apartments](https://housing.sanjoseca.gov/listing/07cc5bd0-4f22-4794-923e-b5de163b8db8/gish_apartments_35_east_gish_road_san_jose_ca) listing (and a few others)

**Expected behavior**
Availability shown in a single place or enforcement that unit-level availability matches property-level availability

**Screenshots**
Gish Apartments example:
<img width="1116" alt="Screenshot 2023-07-12 at 1 35 09 PM" src="https://github.com/housingbayarea/bloom/assets/4656936/781a1f37-1e56-4663-a969-115325db9b30">

Casa Feliz example:
<img width="1088" alt="Screenshot 2023-07-12 at 1 34 09 PM" src="https://github.com/housingbayarea/bloom/assets/4656936/98f8dfc3-6cdd-4c21-82c5-fa1cd694687a">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 114.0.5735.198 

**Additional context**
We try to provide a list of open-waitlist properties to clients of The United Effort Organization.  It is difficult to do so when we can't interpret the listings pages on housing.sanjoseca.gov

**Comment by ludtkemorgan** [comment]
@trevorshannon sorry for the late response on this. We don't believe this is a bug, but rather a semi-confusing language issue. @iph-97 can provide more information

**Comment by trevorshannon** [comment]
Ok, thanks for looking into it @ludtkemorgan and @iph-97 

There may be more linguistic nuance here than we're aware of.  We ([The United Effort Organization](https://theunitedeffort.org)) have been operating with the following mental model in our work to date:

- waitlist open == accepting applications for the waitlist
- vacant unit(s) == accepting applications for the vacant unit(s)

That has served us well so far, but there is probably some edge case we're missing.

**Comment by iph-97** [comment]
Hi Trevor, thanks for getting in touch! I think the difference in the thinking here is that the closed listing preserves the information provided while the listing was open with the exception of the banner at the top of the page and removing the application buttons. Our intention is that an applicant can return to the listing to see exactly what they applied for, but your feedback about how this might be confusing/conflicting is super helpful. So while this is not a bug, I do think this worth investigating further. What's the best way to connect with you/the United Effort Organization to discuss in more detail?

**Comment by trevorshannon** [comment]
You can send me a message at trevor@theunitedeffort.org and we can go from there. Thanks!
