### ISSUE TITLE
Create Alameda Eastlake Apartments Listing - Developer: EBALDC

### ISSUE THREAD

**Issue by antonelitum** [housingbayarea/bloom#66]
Here’s the listing spreadsheet:
https://docs.google.com/spreadsheets/d/1xxEXN0EJvYA6iHbdESmATlV5L6aHc1b443TmicnIuuw/edit#gid=0
Expected launch date: ASAP

**Comment by vubang228** [comment]
@software-project @bk3c There are minor language updates to the listing because some aspects have changes since they last inputted the fields, changes in the spreadsheet below. One big catch they had was that its a First Come First Serve listing, but the What to Expect language was not FCFS. Noted in the spreadsheet as well. 

https://docs.google.com/spreadsheets/d/1xxEXN0EJvYA6iHbdESmATlV5L6aHc1b443TmicnIuuw/edit?usp=sharing

**Comment by bk3c** [comment]
@vubang228 The what to expect language is what we came up with as the neutral version across all listing types -- in the FCFS case, "rank order" is determined by submission time.

Also, I don't think their criminal background text is correct: "Applicants will be denied for the following:1) No history of manufacturing methamhetamines on federal property and 2) No lifetime sex offender registration" is a double negative that I really hope is misplaced. Also, they mis-spelled "methamphetamines". Can I just fix that sentence, or do you want to get a revised one from them?

**Comment by vubang228** [comment]
@bk3c I'll correct it and run it by them to confirm. Also, I was expecting FCFS language to be similar to what we have at Bridgepoint in SMC
![Screen Shot 2020-07-24 at 1 51 52 PM](https://user-images.githubusercontent.com/66143127/88434501-26166d00-cdb5-11ea-97ac-867d3da55283.png)

**Comment by vubang228** [comment]
Yikes, I just noticed we should have that "5 days" there at Bridgepointe, I'll make a comment over there.

**Comment by vubang228** [comment]
@bk3c They confirmed the revised language is ok: 

"Applicants will be denied for the following: 1) History of manufacturing methamphetamines on federal property and 2) Lifetime sex offender registration"

**Comment by software-project** [comment]
@bk3c are you already working on this one or should I grab it?

**Comment by bk3c** [comment]
@software-project Go for it

**Comment by vubang228** [comment]
@bk3c @slowbot, sorry I missed this in the FCFS language. If we're able to come up with general language for FCFS that does not include the words "rank order" that will help with clarity for the applicants and the developers, if we use Bridgepoint language and just make it more general, that sentence could be: 

"Applicants will be contacted on a first come first serve basis until vacancies are filled"

**Comment by software-project** [comment]
@vubang228 we can't change `Application Fees` section without changing it for the whole county. Is that what they are expecting?

**Comment by vubang228** [comment]
@software-project we just talked about using global language for this section, so I'll defer to @slowbot @bk3c 

I'm not sure if that's what you meant when referring to the Application Fee section, to me that section looks fine: 

![Screen Shot 2020-07-28 at 2 08 27 PM](https://user-images.githubusercontent.com/66143127/88722291-d5b44d80-d0db-11ea-9bae-36c34046af8e.png)

**Comment by vubang228** [comment]
I wanted to check back in on this @software-project @bk3c. There are a few items that need updated that are straight forward (Credit History, Rental History, Criminal Background). For the "Application Fee section", are they able to include all that information in that section, or will we need to move that to another one?

**Comment by software-project** [comment]
@vubang228 I've updated Credit History, Criminal Background. Must have missed Rental history somehow. Will prepare a PR now. As mentioned above we cant change `Application Fee section` without effecting whole county.

**Comment by software-project** [comment]
uuuu just one note. As those three fields are plain old strings we can't currently add spacing within sections.

**Comment by vubang228** [comment]
@software-project sorry, I get it now. @slowbot the info they have for the "application fee" section is super important. Should we create another field for "Fee Details" or add to "Costs Not Included"? Here is the text they'd like in this section: 

`$26 application fee per adult. Application fee waived for Section 8 Voucher holders. Unit Holding Fee (upon meeting tenancy requirements & before criminal background check): $250`

**Comment by vubang228** [comment]
@software-project I caught up with @bk3c and we updated the spreadsheet and moved all the language to sections that can fit the text. So the spreadsheet is now up to date and ready for updating the system.

**Comment by bk3c** [comment]
Turns out they got the building leased up before needing it here, so it's permanently disabled in #119
