### ISSUE TITLE
Update text for "Occupancy"

### ISSUE THREAD

**Issue by antonelitum** [housingbayarea/bloom#77]
It should say: Occupancy: "Minimum and maximum occupancy standards for this building differ according to unit type".

**Comment by bk3c** [comment]
@antonelitum I lost the context for this -- where do we need the text changed? It looks correct to me for Alameda...

**Comment by antonelitum** [comment]
@bk3c this needs to occur for all bloom site and now is happening. thanks!

**Comment by antonelitum** [comment]
before, the old language from SF Dalhia was popping up.
