### ISSUE TITLE
Adjust when automatically run pg jobs run

### ISSUE THREAD

**Issue by YazeedLoonat** [housingbayarea/bloom#773]
Description: currently in hba prod the automatic maintenance window for our db is in the middle of the day (today). so it takes our db down if we ever miss a notification in the middle of the day on tuesdays. 

Notes: 
- Currently in production the pg jobs run during the middle of the day, we need to adjust so it happens at a different time. 

https://devcenter.heroku.com/articles/heroku-postgres-maintenance#setting-a-maintenance-window

**Comment by ludtkemorgan** [comment]
This has been completed for HBA.
- New window is 7 - 11 am Wednesdays UTC (midnight pacific)
- HBA staging has been migrated to the new essential tier database from the deprecated mini tier.
  - We are no longer restricted by row number but rather 1gb of space. This will be beneficial to us as we currently only use 13mb but we were getting close to the 10K limit of rows in the old tier. And it doesn't cost any more
  - We are not allowed to set maintenance windows on the essential tier

**Comment by sarahlazarich** [comment]
I don't think this is QA-able by product, right @ludtkemorgan?
