### ISSUE TITLE
Update smc.bloom.exygy.dev with SMC content and listings

### ISSUE THREAD

**Issue by jacchau** [housingbayarea/bloom#9]
Summary: Update smc.bloom.exygy.dev with SMC content from content inventory and listings

- [x] Update smc.bloom.exygy.dev based on the following content inventory https://docs.google.com/spreadsheets/d/1gDOU7Xme1sKR18fviWa-k3QFkcvFTDtlGrpVC4-sjac/edit#gid=378762150

- [x] Create individual listing jsons from listings from smc.housingbayarea.org, listings.id = 3, 7, 8 and related units, application_download_urls, and preferences files (only listing id 3 should have preference information) 

Reference - [smc.housingbayarea.org](url)

**Comment by jacchau** [comment]
Hi @software-project , I've done the same and included QA fixes in the 'QA Change Log' tab, please prioritize these after San Jose. https://docs.google.com/spreadsheets/d/1gDOU7Xme1sKR18fviWa-k3QFkcvFTDtlGrpVC4-sjac/edit#gid=1582711949. Let's merge the PR first and then make the changes. Once you add the listing jsons (with associated units, application download fields), I can go ahead and take a pass to do additional QA and update the listing jsons directly so they match what we have in production.

**Comment by jacchau** [comment]
Hi @software-project, did a quick QA here. One small update - can you update the hero title from 'San Mateo Housing Portal' to 'San Mateo County Housing Portal' please? I am hoping this should take care of 18,19, and 20 from this sheet https://docs.google.com/spreadsheets/d/1gDOU7Xme1sKR18fviWa-k3QFkcvFTDtlGrpVC4-sjac/edit#gid=1582711949. 

The other comment is that the listings images on the browse listing and on the individual listing pages (padding, image, subheadings) have weird formatting. The San Jose and Alameda seems to have the right format. Is there a way to have SMC mirror the same? 

Otherwise the rest of the pages look good. I will work with Ben to figure out the process for creating the listing jsons. 

Examples) 
![image](https://user-images.githubusercontent.com/53061907/78335348-5013fd00-7542-11ea-883c-6446036831e2.png)

![image](https://user-images.githubusercontent.com/53061907/78335486-8b163080-7542-11ea-8d32-59c5fbbceb75.png)

![image](https://user-images.githubusercontent.com/53061907/78335510-979a8900-7542-11ea-9009-d389cee2c7fc.png)

![image](https://user-images.githubusercontent.com/53061907/78335524-9e290080-7542-11ea-9e8f-1c8f9c708a16.png)

**Comment by jacchau** [comment]
@software-project reopenning this issue -After #23 was merged, where should I be QA'ing this? It seems that https://smc.bloom.exygy.dev/listings is referencing the wrong set of listings (Triton, Archer Studios, and Gish) 

For example, the listing id for Triton in smc.bloom.exygy.dev/listings is https://smc.bloom.exygy.dev/listing/jsqvgvy6ejy56tncffqp8 however, the correct listing id for Triton should be "id = 3" https://github.com/housingbayarea/bloom/blob/master/services/listings/listings/triton.json

![image](https://user-images.githubusercontent.com/53061907/79541441-ac951300-803e-11ea-9a7b-716896c32661.png)

**Comment by bk3c** [comment]
Closing this again now that #23 is merged. I expect there are still some minor QA items (both visual and data), but we can file other issues for those as needed.
