### ISSUE TITLE
Create Alameda County Listing - Reilly Station - Eden Housing

### ISSUE THREAD

**Issue by antonelitum** [housingbayarea/bloom#97]
We have a new listing and would need your support to get it on time @pbn4 
Here is the Spreadsheet 
Developer completed 70% of it already and needs a 8/3/2020 launch
https://docs.google.com/spreadsheets/d/1WU0aDSfFrisIY9E7CBqT29OG8lpqbWTYD4IBH6OrpIg/edit?usp=sharing

Let me and Vu-bang if you have questions or are blocked with anything., Thanks

**Comment by vubang228** [comment]
@bk3c @slowbot will it be a problem not having a "Final waitlist Number" for this one? Eden Housing does not want to show it and they are ignoring my request to get it.

**Comment by bk3c** [comment]
I don't have a problem with supporting waitlists of undisclosed/unspecified sizes, but I defer to @slowbot as to whether that's a good idea from an applicant / UX / standardization perspective. I expect it would be relatively straight-forward to make the relevant code changes, but at least some work.

**Comment by bk3c** [comment]
Can we use the image from here? https://edenhousing.org/properties/reilly-station/

**Comment by vubang228** [comment]
@bk3c let's use that as a placeholder? I'm pretty sure they'll want to add a rendering of the development once they get their hands on one to send over

**Comment by pbn4** [comment]
@vubang228 I applied the latest changes. @bk3c If you have any comments please let me know.
